"use client";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { TextField, SelectField, MultiSelect } from "@/components/ui/FormControls";
import { Card, StatCard } from "@/components/ui/Cards";
import { FuelGauge, PieChart, TrendChart } from "@/components/ui/Charts";

export function DesignSystemWorkspace(){
 const [toast,setToast]=useState("");
 const notify=(m:string)=>{setToast(m); window.setTimeout(()=>setToast(""),2200)};
 return <div className="design-system-workspace">
  <section className="page-heading-row"><div><span className="eyebrow">Reusable component library</span><h1>Bite Wise design system</h1><p>Green-led, accessible components designed for consistent implementation across desktop, laptop, tablet, and mobile.</p></div><span className="supportive-badge">WCAG 2.2 AA</span></section>
  <section className="ds-token-grid">
   {[['Primary','#176f45'],['Secondary','#278856'],['Accent','#2669a8'],['Background','#f5f8f6'],['Surface','#ffffff'],['Success','#278856'],['Warning','#8a5b12'],['Error','#b42318'],['Information','#2669a8']].map(([n,v])=><div className="ds-token" key={n}><i style={{background:v}}/><strong>{n}</strong><small>{v}</small></div>)}
  </section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Buttons</span><h2>Clear hierarchy and immediate feedback</h2></div></div><div className="ds-row"><Button onClick={()=>notify('Primary action completed')}>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="text">Text</Button><Button variant="destructive">Destructive</Button><Button disabled>Disabled</Button></div></section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Inputs</span><h2>Accessible form controls</h2></div></div><div className="ds-form-grid"><TextField label="Text field" placeholder="Enter a meal"/><TextField label="Password" type="password" placeholder="At least 8 characters"/><TextField label="Number input" type="number" placeholder="0"/><TextField label="Search" type="search" placeholder="Search meals"/><SelectField label="Dropdown" options={['Nigerian Cuisine','International Cuisine']}/><TextField label="Date picker" type="date"/><MultiSelect label="Dietary preferences" options={['Vegetarian','Halal','Gluten-Free']}/></div></section>
  <section className="ds-card-grid"><StatCard label="Statistics card" value="540 kcal" detail="Remaining today"/><Card eyebrow="Meal card" title="Jollof rice with chicken"><p>Estimated nutrition, serving size, allergens, and one-click logging.</p></Card><Card eyebrow="Recommendation" title="Add beans to your rice"><p>A culturally relevant way to increase protein and fibre.</p></Card><Card eyebrow="Progress" title="Weekly consistency"><div className="progress"><span style={{width:'78%'}}/></div><small>Logged meals on 6 of 7 days</small></Card></section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Charts</span><h2>Responsive, labelled nutrition visuals</h2></div></div><div className="ds-chart-grid"><FuelGauge/><PieChart/><TrendChart/></div></section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Feedback</span><h2>Status is never communicated by colour alone</h2></div></div><div className="ds-feedback"><div className="info-banner"><strong>Information</strong><span>Your nutrition data synchronized successfully.</span></div><div className="warning-banner"><strong>Review needed</strong><span>Calorie values are estimates and may vary.</span></div><div className="success-banner"><strong>Success</strong><span>Your preferences were saved.</span></div><div className="chip-row"><span className="supportive-badge">On track</span><span className="ds-chip">High protein</span><span className="ds-chip">Halal</span></div></div></section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Performance and interaction</span><h2>Production behavior</h2></div></div><ul className="ds-checklist"><li>Lazy-load heavy routes, image analysis, and charts.</li><li>Use responsive images and fixed dimensions to reduce layout shift.</li><li>Cache stable USDA lookups and debounce search requests.</li><li>Paginate meal history and client tables.</li><li>Provide hover, focus, active, loading, success, and reduced-motion states.</li><li>Use 44px minimum touch targets and dynamic text scaling.</li></ul></section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Spacing and elevation</span><h2>Consistent spatial rhythm</h2></div></div><div className="spacing-demo">{[4,8,12,16,24,32,48,64].map(v=><div key={v}><span style={{width:v}}/><small>{v}px</small></div>)}</div><ul className="ds-checklist"><li>12-column desktop grid, 8-column tablet grid, and 4-column mobile grid.</li><li>Page margins: 32px desktop, 24px tablet, and 16px mobile.</li><li>Core radius scale: 10px, 14px, 20px, and 28px.</li><li>Use elevation sparingly: border first, soft shadow for raised or modal surfaces.</li></ul></section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Iconography and illustration</span><h2>Friendly, culturally inclusive visuals</h2></div></div><div className="icon-guidelines"><div><strong>Outlined</strong><p>Default navigation and utility icons, 2px rounded stroke, 20–24px canvas.</p></div><div><strong>Filled</strong><p>Reserved for selected states, critical emphasis, and compact status badges.</p></div><div><strong>Illustrations</strong><p>Simple organic shapes, diverse people and Nigerian/global foods, no stereotypes or clinical fear cues.</p></div></div></section>
  <section className="dashboard-card ds-section"><div className="card-heading"><div><span className="card-kicker">Motion design</span><h2>Subtle and purposeful</h2></div></div><div className="motion-grid"><div><strong>Page transition</strong><span>180–240ms fade and 8px rise</span></div><div><strong>Modal</strong><span>200ms fade and scale</span></div><div><strong>Loading</strong><span>Continuous, low-contrast skeleton</span></div><div><strong>Progress</strong><span>240–300ms eased value change</span></div><div><strong>Success</strong><span>180ms check and gentle emphasis</span></div></div><p className="supportive-note">All motion respects <code>prefers-reduced-motion</code> and never blocks task completion.</p></section>
  {toast&&<div className="app-toast" role="status">✓ {toast}</div>}
 </div>
}
